
### load the diffee library
library(diffee)

graphics.off()
par(ask=F)
par(mfrow=c(1,1))


readline(prompt="Press [enter] to continue to cancer demo with 2 tasks (not v. pcr) and 26 features (26 cancer types) ")

### load cancer data (cancer)
data(cancer)

### create a list of cancer data (cancerlist)
cancerlist = list(as.matrix(cancer[[1]][which(cancer[[2]] == "not"),]),
                  as.matrix(cancer[[1]][which(cancer[[2]] == "pcr"),]))

### run the diffee
result = diffee(cancerlist[[1]], cancerlist[[2]], 40)

### obtain names for node labelling
label = colnames(cancer[[1]])

### obtain graph for creating layout
graph = returngraph.diffee(result)

### create a fixed layout on cancergraph for plotting
layout = layout_nicely(graph,dim=2)

readline(prompt="Press [enter] to display the difference graph generated by diffee")


### plot the estimated graphs by diffee
plot.diffee(result, graphlabel = label, graphlayout = layout)


readline(prompt="Press [enter] to continue to synthetic Gaussian data demo with 2 tasks and 20 features")


### load the  example data
data(exampleData)


### run simule algorithm to estimate two sparse precision matrices from the exampleData
result = diffee(exampleData[[1]], exampleData[[2]], 0.45)


### plot the estimated graphs by diffee

data(exampleDataGraph)
par(mfrow=c(1,2))


layout = layout_nicely(exampleDataGraph[[1]], dim = 2)

readline(prompt="Press [enter] to view comparison between ground truth and generated difference graph")
{
  plot.diffee(result,graphlayout = layout)

  plot.igraph(union(exampleDataGraph[[2]], exampleDataGraph[[3]]),layout = layout,vertex.label.font=2,
              vertex.shape="none",
              vertex.label.color="gray40",
              vertex.label.cex=.7, vertex.frame.color="white", vertex.size = 10 ,
              edge.color = categorical_pal(3)[1],
              main = "difference graph ground truth")
}




readline(prompt="Press [enter] to continue to NIPS word count demo with 2 tasks (before 2006 and after 2006) and 37 features (37 words)")

par(mfrow=c(1,1))

### load nips word count data
data(nip_37_data)

label = colnames(datalist[[1]])

result = diffee(datalist[[1]], datalist[[2]] , 0.0035)

readline(prompt="Press [enter] to display the difference graph")

plot.diffee(result, graphlabel = label)


readline(prompt="Press [enter] to continue to synthetic Gaussian data demo with 2 tasks and 500 features")




data(exampleData500)

readline(prompt="Press [enter] to view the DIFFEE runtime (takes roughly 30 seconds on an i7 machine)")
{
  start_time = Sys.time()
  diffee(exampleData500[[1]], exampleData500[[2]], 1)
  end_time = Sys.time()
  print(paste("the time taken for DIFFEE to run with p = 500 is", end_time - start_time, "seconds"))
}
